server:
  servlet:
    context-path: /
  port: 80
  address: localhost
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/news?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 5Mb
mybatis:
  config-location: classpath:mybatis-config.xml
debug: false

# 打印SQL日志
logging:
  level:
    com:
      cskaoyan:
        distributionnews:
          dao: debug